// Books 
const books = [
  { id: 1, title: '1984', author: 'George Orwell', genre: 'Fiction', length: 'Medium', synopsis: 'George Orwell’s 1984 is a dystopian novel about Winston Smith, a low-ranking member of the ruling Party in Oceania, a totalitarian state under the constant surveillance of Big Brother. In a world defined by perpetual war, "thoughtcrime," and propaganda, Winston attempts to rebel, only to be captured, tortured, and brainwashed into loving the Party. ', prequels: ['None'], sequels: ['None'], image: 'images/1984.jpg', reviews: [{user: 'Reader1', rating: 5, comment: 'Amazing!'}] },
  { id: 2, title: 'Dune', author: 'Frank Herbert', genre: 'Sci-Fi', length: 'Long', synopsis: 'Frank Herberts Dune (1965) is an epic sci-fi masterpiece set in a far-future feudal society, focusing on young Paul Atreides as his noble family takes stewardship of Arrakis, a treacherous desert planet and the only source of the valuable spice melange. After a brutal betrayal by the rival House Harkonnen and the Emperor, Paul escapes into the desert, joins the native Fremen, and embraces his destiny as a prophetic leader, culminating in a struggle for control over the universe. ', prequels: ['Dune: Prophecy'], sequels: ['Dune Messiah', 'Children of Dune'], image: 'images/dune.jpg', reviews: [{user: 'Reader2 ', rating: 4, comment: 'Great world-building.'}] },
  { id: 3, title: 'The Hobbit', author: 'J.R.R. Tolkien', genre: 'Fantasy', length: 'Medium', synopsis: 'The Hobbit by J.R.R. Tolkien follows Bilbo Baggins, a home-loving hobbit recruited by the wizard Gandalf and thirteen dwarves led by Thorin Oakenshield. They journey to reclaim a stolen treasure from the dragon Smaug at the Lonely Mountain. Along the way, Bilbo finds a magic invisibility ring, survives trolls, goblins, and spiders, and matures into a courageous, clever adventurer. ', prequels: ['Nick (2021) by Michael Farris Smith'], sequels: ['Lord of the Rings'], image: 'images/the-hobbit.jpg', reviews: [{user: 'Reader3', rating: 5, comment: 'Fun read.'}] },
  { id: 4, title: 'To Kill a Mockingbird', author: 'Harper Lee', genre: 'Fiction', length: 'Medium', synopsis: 'To Kill a Mockingbird is narrated by young Scout Finch, following her childhood in Depression-era Maycomb, Alabama, where her lawyer father, Atticus, defends Tom Robinson, a Black man falsely accused of raping a white woman, exposing the towns deep-seated racism and leading to a tragic verdict, while Scout and brother Jem learn profound lessons about prejudice, empathy, and courage through the trial and their fascination with their reclusive neighbor, Boo Radley, who ultimately saves them from a vengeful attacker', prequels: ['None'], sequels: ['Go Set a Watchman'], image: 'images/to-kill-a-mockingbird.jpg', reviews: [{user: 'Reader4', rating: 5, comment: 'Timeless classic.'}] },
  { id: 5, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', genre: 'Fiction', length: 'Short', synopsis: 'F. Scott Fitzgerald’s The Great Gatsby (1925) is a tragic tale of ambition, love, and the corruption of the American Dream in 1920s Long Island. Narrated by Nick Carraway, the story follows mysterious millionaire Jay Gatsby, who throws lavish parties to recapture the love of the married, wealthy Daisy Buchanan, ultimately leading to deception, fatal accidents, and Gatsby’s downfall. ', prequels: ['Nick (2021) by Michael Farris Smith'], sequels: ['None'], image: 'images/the-great-gatsby.jpg', reviews: [{user: 'Reader5 ', rating: 4, comment: 'Beautiful prose.'}] },
  { id: 6, title: 'War and Peace', author: 'Leo Tolstoy', genre: 'Fiction', length: 'Long', synopsis: 'War and Peace by Leo Tolstoy is an epic novel chronicling Russian aristocratic families, notably the Bolkonskys, Rostovs, and Bezukhovs, amidst the Napoleonic Wars (1805-1812), exploring their intertwined lives, loves, and search for meaning against grand historical events, culminating in Pierre Bezukhov and Natasha Rostova finding love and family amidst societal upheaval, while Tolstoy argues history is driven by collective actions, not just "great men"', prequels: ['None'], sequels: ['None'], image: 'images/war-and-peace.jpg', reviews: [{user: 'Reader6', rating: 5, comment: 'Masterpiece.'}] },
  { id: 7, title: 'Harry Potter and the Sorcerer\'s Stone', author: 'J.K. Rowling', genre: 'Fantasy', length: 'Medium', synopsis: 'Harry Potter and the Sorcerers Stone follows 11-year-old orphan Harry Potter, who discovers he is a famous wizard. Leaving his neglectful aunt and uncle, he attends Hogwarts School of Witchcraft and Wizardry, befriending Ron Weasley and Hermione Granger. Harry learns to fly, joins the Quidditch team, and thwarts a plot by Lord Voldemort—who murdered his parents—to steal the immortal-granting Sorcerers Stone. ', prequels: ['Fantastic Beasts and Where to Find Them (2016)', 'The Crimes of Grindelwald (2018)', 'The Secrets of Dumbledore (2022)'], sequels: ['Harry Potter and the Chamber of Secrets'], image: 'images/harry-potter-and-the-sorcerers-stone.jpg', reviews: [{user: 'Reader7', rating: 5, comment: 'Magical!'}] },
  { id: 8, title: 'The Lion, the Witch and the Wardrobe', author: 'C.S. Lewis', genre: 'Fantasy', length: 'Short', synopsis: 'The Lion, the Witch and the Wardrobe — "The Chronicles of ...The Lion, the Witch and the Wardrobe by C.S. Lewis follows the four Pevensie children—Peter, Susan, Edmund, and Lucy—who discover a magical, snowy world named Narnia through an old wardrobe. They help the great lion Aslan defeat the evil White Witch, who has cast Narnia into eternal winter, and fulfill a prophecy to become kings and queens. ', prequels: ['The Magicians Nephew (1955) by C.S. Lewis'], sequels: ['Prince Caspian'], image: 'images/the-lion-the-witch-and-the-wardrobe.jpg', reviews: [{user: 'Reader8', rating: 4, comment: 'Enchanting.'}] },
  { id: 9, title: 'The Name of the Wind', author: 'Patrick Rothfuss', genre: 'Fantasy', length: 'Long', synopsis: 'The Name of the Wind by Patrick Rothfuss is a fantasy novel framed as a three-day autobiography told by Kvothe, a legendary, infamous magician now hiding as a humble innkeeper named Kote. It details his childhood in a traveling troupe, his years as a traumatized orphan in the city of Tarbean, and his academic training at a prestigious University to gain power and hunt the Chandrian, the mysterious, mythical figures who murdered his family. ', prequels: ['None'], sequels: ['The Wise Man\'s Fear'], image: 'images/the-name-of-the-wind.jpg', reviews: [{user: 'Reader9', rating: 5, comment: 'Epic fantasy.'}] },
  { id: 10, title: 'Foundation', author: 'Isaac Asimov', genre: 'Sci-Fi', length: 'Medium', synopsis: 'Isaac Asimov’s "Foundation" (1951) follows mathematician Hari Seldon, who uses "psychohistory" to predict the imminent fall of a 12,000-year-old Galactic Empire and a 30,000-year dark age. To reduce this to 1,000 years, Seldon establishes the Foundation, a colony of scientists on the remote planet Terminus designed to preserve knowledge and form a new empire. ', prequels: ['Prelude to Foundation (1988)', ' Forward the Foundation (1993)'], sequels: ['Foundation and Empire'], image: 'images/foundation.jpg', reviews: [{user: 'Reader10', rating: 4, comment: 'Thought-provoking.'}] },
  { id: 11, title: 'Neuromancer', author: 'William Gibson', genre: 'Sci-Fi', length: 'Short', synopsis: 'Neuromancer (1984) by William Gibson is a seminal cyberpunk novel following Case, a washed-up, drug-addicted computer hacker in a dystopian future. After criminals damage his nervous system, preventing him from accessing the "Matrix" (cyberspace), a mercenary named Molly Millions recruits him for a high-stakes heist.', prequels: ['None'], sequels: ['Count Zero'], image: 'images/neuromancer.jpg', reviews: [{user: 'Reader11', rating: 5, comment: 'Groundbreaking.'}] },
  { id: 12, title: 'The Left Hand of Darkness', author: 'Ursula K. Le Guin', genre: 'Sci-Fi', length: 'Long', synopsis: 'The Left Hand of Darkness (1969) by Ursula K. Le Guin is a landmark science fiction novel following Genly Ai, a human envoy sent to the frozen planet Gethen (Winter) to convince its inhabitants to join an intergalactic alliance, the Ekumen. Gethenians are ambisexual with no fixed gender, creating a unique society that challenges Ai’s perceptions of gender, sexuality, and politics. ', prequels: ['None'], sequels: ['None'], image: 'images/the-left-hand-of-darkness.jpg', reviews: [{user: 'Reader12', rating: 5, comment: 'Profound.'}] },
  { id: 13, title: 'Pride and Prejudice', author: 'Jane Austen', genre: 'Fiction', length: 'Medium', synopsis: 'Pride and Prejudice by Jane Austen follows witty Elizabeth Bennet, one of five daughters in a landed gentry family, as she navigates societal expectations and romance in early 19th-century England, clashing with the wealthy, haughty Mr. Fitzwilliam Darcy due to their initial pride and prejudice, ultimately overcoming these flaws to fall in love, mirroring her sister Janes milder romance with Darcys friend Mr. Bingley, all while critiquing class and marriage customs', prequels: ['Vanity and Verity by Jeanne Waters', 'the Fitzwilliam Darcy, Gentleman trilogy by Pamela Aidan'], sequels: ['Death Comes to Pemberley by P.D. James', 'Mr. Darcy Takes a Wife by Linda Berdoll', 'The Darcys of Pemberley by Shannon Winslow'], image: 'images/pride-and-prejudice.jpg', reviews: [{user: 'Reader13', rating: 4, comment: 'Witty and charming.'}] }
];

// Authors for Author of the Day
const authors = [
  'George Orwell',
  'Frank Herbert',
  'J.R.R. Tolkien',
  'Harper Lee',
  'F. Scott Fitzgerald',
  'Leo Tolstoy',
  'J.K. Rowling',
  'C.S. Lewis',
  'Patrick Rothfuss',
  'Isaac Asimov',
  'William Gibson',
  'Ursula K. Le Guin',
  'Jane Austen'
];

// Quotes for rotator
const quotes = [
  '"Books are a uniquely portable magic." - Stephen King',
  '"The journey of a thousand miles begins with a single page." - Adapted from Lao Tzu',
  '"Reading is dreaming with open eyes." - Unknown',
  '"A reader lives a thousand lives before he dies. The man who never reads lives only one." - George R.R. Martin',
  '"There is no friend as loyal as a book." - Ernest Hemingway',
  '"Books are the plane, and the train, and the road. They are the destination, and the journey." - Anna Quindlen',
  '"I have always imagined that Paradise will be a kind of library." - Jorge Luis Borges',
  '"The more that you read, the more things you will know. The more that you learn, the more places you\'ll go." - Dr. Seuss',
  '"Books may well be the only true magic." - Alice Hoffman',
  '"A book is a dream that you hold in your hand." - Neil Gaiman',
  '"Reading is to the mind what exercise is to the body." - Joseph Addison',
  '"One glance at a book and you hear the voice of another person, perhaps someone dead for 1,000 years." - Carl Sagan',
  '"Books are mirrors: you only see in them what you already have inside you." - Carlos Ruiz Zafón'
];